### ISSUE TITLE
Couldn't resolve parser "solidity-parse"

### ISSUE THREAD

**Issue by does1tmatter** [dl-solarity/hardhat-markup#17]
Running `npx hardhat markup` throws following error:

```
Compiled 99 Solidity files successfully

Generating markups...
Error in plugin @solarity/hardhat-markup: Couldn't resolve parser "solidity-parse"
```

Honestly no idea where to start debugging.
Stack trace:
```
NomicLabsHardhatPluginError: Couldn't resolve parser "solidity-parse"
    at SimpleTaskDefinition.markup (D:\...\node_modules\@solarity\hardhat-markup\src\index.ts:39:4)
    at Environment._runTaskDefinition (D:\...\node_modules\hardhat\src\internal\core\runtime-environment.ts:333:14)
    at Environment.run (D:\...\node_modules\hardhat\src\internal\core\runtime-environment.ts:166:14)
    at main (D:\...\node_modules\hardhat\src\internal\cli\cli.ts:280:7)
```

**Comment by z0rats** [comment]
I had the same issue.
Fixed by downgrading prettier version:
```
"eslint-plugin-prettier": "^4.2.1",
"prettier": "2.8.8",
```
